trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  suffix: '$(Build.BuildNumber)'

steps:
- pwsh: .\SetupEnvironment.ps1
  displayName: 'Setup the environment'

- pwsh: Invoke-Build Build -Suffix $(suffix)
  displayName: 'Build the library'

- pwsh: Invoke-Build Pack -Suffix $(suffix)
  displayName: 'Pack the build'