trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  suffix: ''
  nugetSource: 'https://api.nuget.org/v3/index.json'

steps:
- pwsh: .\SetupEnvironment.ps1
  displayName: 'Setup the environment'

- pwsh: Invoke-Build Build -Suffix "$(suffix)"
  displayName: 'Build the library'

- pwsh: Invoke-Build Pack -Suffix "$(suffix)"
  displayName: 'Pack the build'

- task: NuGetAuthenticate@1

- pwsh: Invoke-Build Deploy -NugetSource "$(nugetSource)" -NugetApiKey $env:ENV_NUGET_APIKEY
  displayName: 'Deploy the package'
  env:
    ENV_NUGET_APIKEY: $(NUGET_APIKEY)