trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables: 
  suffix: '$(Build.BuildNumber)'

steps:
- pwsh: .\SetupEnvironment.ps1
  displayName: 'Setup the environment'

- pwsh: Invoke-Build Build -Suffix $(suffix)
  displayName: 'Build the library'

- pwsh: Invoke-Build Pack -Suffix $(suffix)
  displayName: 'Pack the build'

- task: NuGetAuthenticate@0

- pwsh: Invoke-Build Deploy -NugetSource "https://marcuswalther.pkgs.visualstudio.com/EnvironmentModuleCoreSrc/_packaging/EnvironmentModuleCoreSrc_Feed/nuget/v3/index.json" -NugetApiKey AzureArtifacts
  displayName: 'Deploy the package'